import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Bell, BellOff, CheckCheck, Trash2, Repeat, Calendar, Briefcase, Award,
  MessageSquare, TrendingUp, Megaphone, Info, Clock, ArrowRight, RefreshCw, Zap,
} from 'lucide-react';
import { notificationAPI, dashboardAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import {
  PageHeader, LoadingScreen, EmptyState, Badge, MotionCard, Tabs,
  Spinner, Callout, StatCard,
} from '../components/ui/Primitives';

const TYPE_META = {
  revision: { icon: Repeat, tone: 'cyan', label: 'Revision' },
  deadline: { icon: Calendar, tone: 'coral', label: 'Deadline' },
  opportunity: { icon: Briefcase, tone: 'violet', label: 'Opportunity' },
  application: { icon: TrendingUp, tone: 'mint', label: 'Application' },
  achievement: { icon: Award, tone: 'amber', label: 'Achievement' },
  room: { icon: MessageSquare, tone: 'violet', label: 'Peer room' },
  announcement: { icon: Megaphone, tone: 'amber', label: 'Announcement' },
  profile: { icon: Info, tone: 'slate', label: 'Profile' },
  quiz: { icon: Zap, tone: 'cyan', label: 'Quiz' },
  system: { icon: Bell, tone: 'slate', label: 'System' },
};

const meta = (t) => TYPE_META[t] || TYPE_META.system;

export default function Notifications() {
  const { user } = useAuth();
  const toast = useToast();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [busy, setBusy] = useState('');

  const load = async () => {
    try {
      const d = await notificationAPI.list();
      setItems(d.notifications || []);
    } catch (e) {
      toast.error(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const markRead = async (n) => {
    if (n.isRead) return;
    setBusy(n._id);
    try {
      await notificationAPI.markRead(n._id);
      setItems((list) => list.map((x) => (String(x._id) === String(n._id) ? { ...x, isRead: true } : x)));
    } catch (e) {
      toast.error(e.message);
    } finally {
      setBusy('');
    }
  };

  const markAll = async () => {
    setBusy('all');
    try {
      await notificationAPI.markAllRead();
      toast.success('All caught up');
      load();
    } catch (e) {
      toast.error(e.message);
    } finally {
      setBusy('');
    }
  };

  const remove = async (n) => {
    setBusy(n._id);
    try {
      await notificationAPI.remove(n._id);
      setItems((list) => list.filter((x) => String(x._id) !== String(n._id)));
    } catch (e) {
      toast.error(e.message);
    } finally {
      setBusy('');
    }
  };

  const runReminders = async () => {
    setBusy('cron');
    try {
      const d = await dashboardAPI.runReminders();
      toast.success(
        `Reminder job ran: ${d.revisions} revision, ${d.deadlines} deadline and ${d.profiles} profile notification(s) created.`
      );
      load();
    } catch (e) {
      toast.error(e.message);
    } finally {
      setBusy('');
    }
  };

  if (loading) return <LoadingScreen label="Loading notifications…" />;

  const unread = items.filter((n) => !n.isRead);
  const types = [...new Set(items.map((n) => n.type))];
  const shown =
    filter === 'all' ? items :
    filter === 'unread' ? unread :
    items.filter((n) => n.type === filter);

  return (
    <div className="space-y-5">
      <PageHeader
        icon={Bell}
        title="Notifications"
        subtitle="Deadline warnings, revision reminders and pipeline moves — generated by real scheduled jobs, not fake badges."
        badge={unread.length > 0 && <Badge tone="coral">{unread.length} unread</Badge>}
        action={
          <>
            {user?.role === 'admin' && (
              <button onClick={runReminders} disabled={busy === 'cron'} className="btn-secondary">
                {busy === 'cron' ? <Spinner size={14} /> : <RefreshCw size={15} />} Run reminder job
              </button>
            )}
            {unread.length > 0 && (
              <button onClick={markAll} disabled={busy === 'all'} className="btn-primary">
                {busy === 'all' ? <Spinner size={14} /> : <CheckCheck size={15} />} Mark all read
              </button>
            )}
          </>
        }
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <StatCard icon={Bell} label="Total" value={items.length} sub="All notifications" tone="violet" />
        <StatCard icon={BellOff} label="Unread" value={unread.length} sub="Need your attention" tone="coral" delay={0.06} />
        <StatCard icon={Repeat} label="Revision" value={items.filter((n) => n.type === 'revision').length} sub="Spaced repetition" tone="cyan" delay={0.12} />
        <StatCard icon={Calendar} label="Deadlines" value={items.filter((n) => n.type === 'deadline').length} sub="Closing soon" tone="amber" delay={0.18} />
      </div>

      <Callout tone="violet" icon={Clock} title="Where these come from">
        A <strong>node-cron</strong> scheduler runs inside the Express server: a daily 07:00 sweep for revisions due,
        deadlines within three days, profiles under 80% complete and pending quizzes; an hourly job that expires
        closed drives; and a 30-minute revision check. Every notification carries a dedupe key so you never get the
        same nudge twice.
      </Callout>

      <div className="flex gap-1.5 flex-wrap">
        <button
          onClick={() => setFilter('all')}
          className={`px-3 py-1.5 rounded-lg text-[12px] font-semibold border transition-all ${
            filter === 'all' ? 'border-orbit-violet/50 bg-orbit-violet/15 text-white' : 'border-white/10 text-slate-400 hover:border-white/25'
          }`}
        >
          All ({items.length})
        </button>
        <button
          onClick={() => setFilter('unread')}
          className={`px-3 py-1.5 rounded-lg text-[12px] font-semibold border transition-all ${
            filter === 'unread' ? 'border-rose-400/50 bg-rose-400/15 text-white' : 'border-white/10 text-slate-400 hover:border-white/25'
          }`}
        >
          Unread ({unread.length})
        </button>
        {types.map((t) => {
          const m = meta(t);
          return (
            <button
              key={t}
              onClick={() => setFilter(t)}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[12px] font-semibold border transition-all ${
                filter === t ? 'border-orbit-violet/50 bg-orbit-violet/15 text-white' : 'border-white/10 text-slate-400 hover:border-white/25'
              }`}
            >
              <m.icon size={12} /> {m.label} ({items.filter((n) => n.type === t).length})
            </button>
          );
        })}
      </div>

      {shown.length === 0 ? (
        <MotionCard hover={false} className="p-8">
          <EmptyState
            icon={items.length ? Bell : BellOff}
            title={items.length ? 'Nothing here' : 'No notifications yet'}
            description={
              items.length
                ? 'No notifications match this filter.'
                : 'When a revision falls due or a drive deadline approaches, you will hear about it here.'
            }
          />
        </MotionCard>
      ) : (
        <div className="space-y-2.5">
          <AnimatePresence mode="popLayout">
            {shown.map((n, i) => {
              const m = meta(n.type);
              const Icon = m.icon;
              return (
                <motion.div
                  key={n._id}
                  layout
                  initial={{ opacity: 0, x: -16 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20, height: 0 }}
                  transition={{ delay: Math.min(i * 0.03, 0.25) }}
                  onClick={() => markRead(n)}
                  className={`group relative rounded-xl border p-4 transition-all cursor-pointer ${
                    n.isRead
                      ? 'border-white/[0.06] bg-white/[0.018] hover:bg-white/[0.035]'
                      : 'border-orbit-violet/28 bg-orbit-violet/[0.07] hover:bg-orbit-violet/[0.1]'
                  }`}
                >
                  {!n.isRead && (
                    <span className="absolute left-0 top-1/2 -translate-y-1/2 w-1 h-8 rounded-r-full bg-gradient-to-b from-orbit-violet to-orbit-cyan" />
                  )}

                  <div className="flex items-start gap-3.5">
                    <div
                      className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 border ${
                        n.isRead ? 'bg-white/[0.045] border-white/[0.08]' : 'bg-orbit-violet/15 border-orbit-violet/28'
                      }`}
                    >
                      <Icon size={17} className={n.isRead ? 'text-slate-500' : 'text-orbit-violet'} />
                    </div>

                    <div className="min-w-0 flex-1">
                      <div className="flex items-start justify-between gap-3 mb-1">
                        <p className={`text-[13.5px] font-semibold leading-snug ${n.isRead ? 'text-slate-300' : 'text-white'}`}>
                          {n.title}
                        </p>
                        <div className="flex items-center gap-2 shrink-0">
                          <Badge tone={m.tone}>{m.label}</Badge>
                          {n.priority === 'high' && <Badge tone="coral">Urgent</Badge>}
                        </div>
                      </div>

                      <p className={`text-[12.5px] leading-relaxed ${n.isRead ? 'text-slate-500' : 'text-slate-300'}`}>
                        {n.body}
                      </p>

                      <div className="flex items-center justify-between gap-3 mt-2.5 flex-wrap">
                        <span className="text-[10.5px] text-slate-600 flex items-center gap-1.5">
                          <Clock size={10} /> {new Date(n.createdAt).toLocaleString('en-IN', {
                            day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit',
                          })}
                        </span>

                        <div className="flex items-center gap-2">
                          {n.link && (
                            <Link
                              to={n.link}
                              onClick={(e) => { e.stopPropagation(); markRead(n); }}
                              className="text-[11.5px] font-semibold text-orbit-cyan hover:underline inline-flex items-center gap-1"
                            >
                              {n.actionLabel || 'Open'} <ArrowRight size={11} />
                            </Link>
                          )}
                          <button
                            onClick={(e) => { e.stopPropagation(); remove(n); }}
                            disabled={busy === n._id}
                            className="opacity-0 group-hover:opacity-100 transition-opacity text-slate-600 hover:text-rose-400 p-1"
                            aria-label="Delete notification"
                          >
                            {busy === n._id ? <Spinner size={12} /> : <Trash2 size={12} />}
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      )}
    </div>
  );
}
